### ISSUE TITLE
Encrypted rooms don't work?

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/trinity#14]
Maybe something is required to make it work with encrypted rooms, but this has not worked during the demo with Flaki.

**Comment by bnjbvr** [comment]
Still valid as of today. Might be an issue in matrix-rust-sdk.

**Comment by ahal** [comment]
I've run into this a few times, and clobbering my store gets it going again. I'm not sure under what conditions the store is invalidated, as I can definitely stop / restart the bot in most cases and it'll connect to encrypted rooms just fine.
